/// Generates the PPD for a model. Option keywords here are the ones `rastertobrother` looks up.
public enum PPDGenerator {
    public static let driverVersion = "0.1"
    /// Absolute because `/usr/libexec/cups/filter` is read-only on macOS.
    public static let filterPath = "/Library/Printers/BrotherOSS/filter/rastertobrother"

    public static func ppd(for model: PrinterModel) -> String {
        var out = Lines()

        out += "*PPD-Adobe: \"4.3\""
        out += "*% Generated by brother-mac-driver. Do not edit; change PPDGenerator.swift instead."
        out += "*FormatVersion: \"4.3\""
        out += "*FileVersion: \"\(driverVersion)\""
        out += "*LanguageVersion: English"
        out += "*LanguageEncoding: ISOLatin1"
        out += "*PCFileName: \"\(pcFileName(model))\""
        out += "*Manufacturer: \"Brother\""
        out += "*Product: \"(\(model.name))\""
        out += "*ModelName: \"\(model.makeAndModel)\""
        out += "*ShortNickName: \"\(model.makeAndModel)\""
        out += "*NickName: \"\(model.makeAndModel), brother-mac-driver \(driverVersion)\""
        out += "*PSVersion: \"(3010.000) 0\""
        out += "*LanguageLevel: \"3\""
        out += "*ColorDevice: \(model.color ? "True" : "False")"
        out += "*DefaultColorSpace: \(model.color ? "RGB" : "Gray")"
        out += "*FileSystem: False"
        out += "*Throughput: \"\(model.pagesPerMinute)\""
        out += "*LandscapeOrientation: Plus90"
        out += "*TTRasterizer: Type42"
        out += "*1284DeviceID: \"MFG:Brother;MDL:\(model.name);\""
        out += "*cupsVersion: 2.3"
        out += "*cupsModelNumber: 0"
        // Copies are produced upstream as repeated pages, which keeps collation right without printer memory.
        out += "*cupsManualCopies: True"
        out += "*cupsFilter: \"application/vnd.cups-raster 50 \(filterPath)\""
        out += "*cupsLanguages: \"en\""
        out += "*BRBackend: \"\(model.backend.rawValue)\""
        out += ""

        pageSizes(&out, model)
        resolution(&out)
        if model.color { colorModel(&out) }
        if model.duplex { duplex(&out) }
        pickOne(
            &out, keyword: "InputSlot", title: "Paper Source", defaultChoice: "Auto",
            choices: model.inputSlots.map { ($0.keyword, $0.displayName, "") })
        pickOne(
            &out, keyword: "BRTonerSaveMode", title: "Toner Save Mode", defaultChoice: "OFF",
            choices: [("OFF", "Off", ""), ("ON", "On", "")])

        out += "*OpenGroup: Advanced/Advanced"
        out += ""
        pickOne(
            &out, keyword: "BRCompression", title: "Data Compression", defaultChoice: "RLE",
            choices: [("RLE", "Standard (RLE)", ""), ("DeltaRow", "Smaller (Delta Row)", "")])
        pickOne(
            &out, keyword: "BRPJL", title: "Brother Job Settings (PJL)", defaultChoice: "ON",
            choices: [("ON", "Send", ""), ("OFF", "Do Not Send", "")])
        pickOne(
            &out, keyword: "BRErrorPage", title: "Print Error Report Page", defaultChoice: "OFF",
            choices: [("OFF", "Off", ""), ("ON", "On", "")])
        out += "*CloseGroup: Advanced"
        out += ""

        out += "*DefaultFont: Courier"
        out += "*Font Courier: Standard \"(1.05)\" Standard ROM"
        return out.text
    }

    // MARK: Sections

    private static func pageSizes(_ out: inout Lines, _ model: PrinterModel) {
        let sizes = model.mediaSizes
        for keyword in ["PageSize", "PageRegion"] {
            out += "*OpenUI *\(keyword)/\(keyword == "PageSize" ? "Media Size" : "Page Region"): PickOne"
            out += "*OrderDependency: 10 AnySetup *\(keyword)"
            out += "*Default\(keyword): Letter"
            for size in sizes {
                out += "*\(keyword) \(size.ppdName)/\(ascii(size.displayName)): "
                    + "\"<</PageSize[\(number(size.widthPoints)) \(number(size.heightPoints))]/ImagingBBox null>>setpagedevice\""
            }
            out += "*CloseUI: *\(keyword)"
            out += ""
        }

        out += "*DefaultImageableArea: Letter"
        for size in sizes {
            let margins = model.margins ?? PrinterModel.Margins(
                left: size.marginPoints, bottom: size.marginPoints, right: size.marginPoints, top: size.marginPoints)
            out += "*ImageableArea \(size.ppdName)/\(ascii(size.displayName)): "
                + "\"\(number(margins.left)) \(number(margins.bottom)) "
                + "\(number(size.widthPoints - margins.right)) \(number(size.heightPoints - margins.top))\""
        }
        out += ""
        out += "*DefaultPaperDimension: Letter"
        for size in sizes {
            out += "*PaperDimension \(size.ppdName)/\(ascii(size.displayName)): "
                + "\"\(number(size.widthPoints)) \(number(size.heightPoints))\""
        }
        out += ""
    }

    private static func resolution(_ out: inout Lines) {
        pickOne(
            &out, keyword: "Resolution", title: "Resolution", defaultChoice: "600dpi",
            choices: [("600dpi", "600 dpi", "<</HWResolution[600 600]>>setpagedevice")])
    }

    private static func colorModel(_ out: inout Lines) {
        // cupsColorSpace 19 = sRGB, 18 = sGray (gamma 2.2 luminance, 0 = black).
        let rgb = "<</cupsColorSpace 19/cupsColorOrder 0/cupsBitsPerColor 8>>setpagedevice"
        let gray = "<</cupsColorSpace 18/cupsColorOrder 0/cupsBitsPerColor 8>>setpagedevice"
        pickOne(
            &out, keyword: "ColorModel", title: "Color Mode", defaultChoice: "Auto",
            choices: [("Auto", "Auto", rgb), ("RGB", "Color", rgb), ("Gray", "Black and White", gray)])
    }

    private static func duplex(_ out: inout Lines) {
        pickOne(
            &out, keyword: "Duplex", title: "Two-Sided", defaultChoice: "None",
            choices: [
                ("None", "Off", "<</Duplex false>>setpagedevice"),
                ("DuplexNoTumble", "Long-Edge Binding", "<</Duplex true/Tumble false>>setpagedevice"),
                ("DuplexTumble", "Short-Edge Binding", "<</Duplex true/Tumble true>>setpagedevice"),
            ])
        // The printer turns the back side itself (PCL XL DuplexPageMode), so back pages arrive unrotated.
        out += "*cupsBackSide: Normal"
        out += ""
    }

    private static func pickOne(
        _ out: inout Lines, keyword: String, title: String, defaultChoice: String,
        choices: [(keyword: String, title: String, code: String)]
    ) {
        out += "*OpenUI *\(keyword)/\(title): PickOne"
        out += "*OrderDependency: 10 AnySetup *\(keyword)"
        out += "*Default\(keyword): \(defaultChoice)"
        for choice in choices {
            out += "*\(keyword) \(choice.keyword)/\(choice.title): \"\(choice.code)\""
        }
        out += "*CloseUI: *\(keyword)"
        out += ""
    }

    // MARK: Formatting

    /// 8.3 upper-case file name, as the PPD specification requires: `BR` + up to six model characters.
    static func pcFileName(_ model: PrinterModel) -> String {
        let name = model.name.hasSuffix(" series") ? String(model.name.dropLast(7)) : model.name
        let stem = name.uppercased().filter { $0.isASCII && ($0.isLetter || $0.isNumber) }
        return "BR\(stem.suffix(6)).PPD"
    }

    /// PPD translation strings here are declared ISOLatin1; keep them plain ASCII.
    static func ascii(_ text: String) -> String {
        String(text.map { $0 == "×" ? "x" : $0 }.filter(\.isASCII))
    }

    private static func number(_ value: Double) -> String {
        value == value.rounded() ? String(Int(value)) : String(value)
    }

    private struct Lines {
        var text = ""
        static func += (lines: inout Lines, line: String) {
            lines.text += line + "\n"
        }
    }
}
